### ISSUE TITLE
Case Insensitive Searches

### ISSUE THREAD

**Issue by e305832** [Brownshome/FolderSearch#4]
How do I use the /i flag (for case insensitivity) in a rule?

**Comment by Brownshome** [comment]
`(?i)` turns on case insensitivity, and `(?-i)` turns off case insensitivity.

e.g. `(?<line>^.*?(\W|^)(?i)%search%(?-i)(\W|$).*$)`

**Comment by Brownshome** [comment]
On further examination, as the `%search%` term is treated as a single character, it does not respect the flags.

**Comment by Brownshome** [comment]
Should be fixed in 7782c9d9d51b79cb121b106fc774d0aa9ecbafae
